# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[package]
disabled = true

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[✗](bold red)"

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[directory]
truncation_symbol = "…/"

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
